name: Angular CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install Angular CLI
        run: npm install -g @angular/cli@10.0.1

      - name: Install project dependencies
        run: npm install

      - name: Build Angular app
        run: ng build --prod

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./dist/client # Adjust this path to your Angular app build output
          
