name: CI/CD for Angular

on:
  push:
    branches:
      - main # Change this to your main branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14 # Change this to your preferred Node.js version

      - name: Install dependencies
        run: npm install

      - name: Build Angular app
        run: npm run build

      - name: Run tests
        run: npm test

      - name: Deploy to hosting (e.g., Firebase, Netlify)
        # Add your deployment steps here, if applicable
